"""empty message

Revision ID: 40b75a4ffcc1
Revises: 
Create Date: 2025-08-06 22:37:58.874940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40b75a4ffcc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusionpattern',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exclusionpattern_name'), 'exclusionpattern', ['name'], unique=True)
    op.create_table('file',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('directory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('extracted_info', sa.JSON(), nullable=True),
    sa.Column('extraction_failed', sa.Boolean(), nullable=False),
    sa.Column('extraction_failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_full_path'), 'file', ['full_path'], unique=True)
    op.create_table('filechangepattern',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('regex_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('replacement_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filechangepattern_name'), 'filechangepattern', ['name'], unique=True)
    op.create_table('extracteddata',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('extracted_values', sa.JSON(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('episode_start_date', sa.DateTime(), nullable=True),
    sa.Column('episode_end_date', sa.DateTime(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['filechangepattern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracteddata_file_id'), 'extracteddata', ['file_id'], unique=False)
    op.create_index(op.f('ix_extracteddata_pattern_id'), 'extracteddata', ['pattern_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracteddata_pattern_id'), table_name='extracteddata')
    op.drop_index(op.f('ix_extracteddata_file_id'), table_name='extracteddata')
    op.drop_table('extracteddata')
    op.drop_index(op.f('ix_filechangepattern_name'), table_name='filechangepattern')
    op.drop_table('filechangepattern')
    op.drop_index(op.f('ix_file_full_path'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_exclusionpattern_name'), table_name='exclusionpattern')
    op.drop_table('exclusionpattern')
    # ### end Alembic commands ###
