"""Recreate exclusionpattern table

Revision ID: 43b2e8eb5251
Revises: 784ac1e1b9aa
Create Date: 2025-08-06 18:04:50.373171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b2e8eb5251'
down_revision: Union[str, Sequence[str], None] = '784ac1e1b9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
