"""Update ExtractedData model with JSON type

Revision ID: 784ac1e1b9aa
Revises: aa87cdb7e1a5
Create Date: 2025-08-06 18:01:32.321878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784ac1e1b9aa'
down_revision: Union[str, Sequence[str], None] = 'aa87cdb7e1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exclusionpattern_name'), table_name='exclusionpattern')
    op.drop_table('exclusionpattern')
    with op.batch_alter_table('extracteddata', schema=None) as batch_op:
        batch_op.alter_column('extracted_values',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracteddata', schema=None) as batch_op:
        batch_op.alter_column('extracted_values',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=False)

    op.create_table('exclusionpattern',
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('pattern', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exclusionpattern_name'), 'exclusionpattern', ['name'], unique=1)
    # ### end Alembic commands ###
