"""Add FileChangeRequest and FileChangeRequestTarget tables

Revision ID: 98d464063607
Revises: 40b75a4ffcc1
Create Date: 2025-08-08 17:13:30.351120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '98d464063607'
down_revision: Union[str, None] = '40b75a4ffcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

import app.domain.custom_types

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.alter_column('extracted_info', 
               existing_type=sa.JSON(), 
               type_=app.domain.custom_types.JsonEncodedDict(), 
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'extracted_info',
               existing_type=app.domain.custom_types.JsonEncodedDict(),
               type_=sqlite.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
