"""autogenerate revision

Revision ID: aa87cdb7e1a5
Revises: b92b7826c085
Create Date: 2025-08-06 17:52:53.369339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa87cdb7e1a5'
down_revision: Union[str, Sequence[str], None] = 'b92b7826c085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exclusionpattern_name'), table_name='exclusionpattern')
    op.drop_table('exclusionpattern')
    op.add_column('file', sa.Column('extracted_info', sa.JSON(), nullable=True))
    op.add_column('filechangepattern', sa.Column('is_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filechangepattern', 'is_confirmed')
    op.drop_column('file', 'extracted_info')
    op.create_table('exclusionpattern',
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('pattern', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exclusionpattern_name'), 'exclusionpattern', ['name'], unique=1)
    # ### end Alembic commands ###
